const DATA={
"1":[
 {title:"Daily Ops in one page",summary:"Use this when you need the shortest safe routine.",steps:["Open Site Operations and scan projects that need attention.","Read Slack/site evidence before changing any project fact.","Classify the fact correctly: work, blocker, readiness, stock, usage, instruction, plan or evidence.","Update the canonical owning file once; append history when operational truth changes.","Check GitHub Actions, then verify the public page and downstream Sheet/Slack projection."],tip:"Stock is not consumption. A photo without context is not completion. Unknown stays unknown.",links:[["Open Site Operations","site-operations.html"],["Open Workspace","workspace/"],["Open GitHub Actions","https://github.com/FabinGurung/JP_Communication-Command-Centre-and-Resource-Hub/actions"]]}
],
"3":[
 {title:"1 · Find the right project and source",summary:"Start from the human-facing dashboard, then trace back to the owning source.",steps:["Open the Workspace when you are unsure where to go.","Use Site Operations for today's work/readiness and Project Map for location/master context.","Open the individual project page for work, blockers, materials, evidence and Drive-backed resources."],tip:"Do not edit rendered HTML to fix a data fact. Fix the owning CSV/JSON/Drive/Sheet source.",links:[["Workspace","workspace/"],["Site Operations","site-operations.html"],["Project Map","map.html"]]},
 {title:"2 · Reconcile field evidence",summary:"Turn field messages into precise operational facts without inventing certainty.",steps:["Read the Slack message/photo/file and identify the project.","Separate observation from inference: stock, usage, work status and instruction are different facts.","Write current operational state to current-works.json and append a matching JSONL event when warranted.","If evidence conflicts or is ambiguous, preserve UNRESOLVED / NEEDS_INPUT / HOLD."],tip:"The system is evidence-first, not optimism-first.",links:[["Current state","ops/data/current-works.json"],["Event history","ops/events/daily-ops-events.jsonl"]]},
 {title:"3 · Verify publication and follow up",summary:"A write is not complete until the provider and the public view agree.",steps:["Run/observe GitHub Actions for the intended branch head.","Confirm validation and Pages deployment succeeded.","Open the live page and verify the expected project/resource appears.","Project controlled summaries to Sheets/Slack; do not create a second independent truth store."],tip:"Provider readback is part of completion.",links:[["GitHub Actions","https://github.com/FabinGurung/JP_Communication-Command-Centre-and-Resource-Hub/actions"],["Workspace","workspace/"]]}
],
"7":[
 {title:"1 · Morning orientation",summary:"Know what needs attention before asking the field for more information.",steps:["Open Site Operations.","Review blockers, HOLD/NEEDS_INPUT and stale projects.","Open the Workspace only when you need a source/tool/module."],links:[["Site Operations","site-operations.html"],["Workspace","workspace/"]]},
 {title:"2 · Read field evidence",summary:"Slack and Drive are evidence/input surfaces.",steps:["Read the latest tracker replies and supporting media.","Identify the exact project and timestamp.","Reject cross-project attribution unless supported."],tip:"A message can be true but belong to the wrong site."},
 {title:"3 · Admit the fact",summary:"Convert evidence into a precise state.",steps:["Choose work/readiness/material/blocker/evidence type.","Preserve quantity and unit exactly.","Use UNKNOWN or UNRESOLVED when meaning is unclear."],tip:"Never derive cement consumption from stock differences unless the source supports it."},
 {title:"4 · Update canonical files",summary:"One fact should have one owning source.",steps:["Project master → projects.csv.","Daily Ops current truth → current-works.json.","History → daily-ops-events.jsonl.","Engineering file relationship → project-resources.json; actual file stays in Drive."],links:[["Current state","ops/data/current-works.json"],["Resources","ops/data/project-resources.json"]]},
 {title:"5 · Validate and publish",summary:"Let automation catch structural mistakes.",steps:["Commit on the governed branch.","Wait for the intended GitHub Actions run.","Treat cancelled intermediate runs as superseded only when the final intended head passes."],links:[["Actions","https://github.com/FabinGurung/JP_Communication-Command-Centre-and-Resource-Hub/actions"]]},
 {title:"6 · Project to people",summary:"Sheets and Slack exist for humans.",steps:["Project the validated state to the appropriate Sheet.","Send concise Slack questions only for unresolved items.","Read back the provider objects before calling the cycle closed."]},
 {title:"7 · Close safely",summary:"Use A9 for material changes and durable releases.",steps:["PRE snapshot before material mutation.","Preserve stable IDs and append-only history.","Provider readback after writes.","POST snapshot and Local/Main synchronization when the workstream requires durable registration."],tip:"A9 is a recovery/audit discipline, not permission to duplicate facts everywhere."}
],
"15":[
 {title:"1 · What the Operations Hub is",summary:"The human-facing operations layer of the JP AEC platform.",steps:["Map = project/master context.","Site Operations = current execution context.","Workspace = navigation and source ownership.","Guide = training and SOP."]},
 {title:"2 · Project identity",summary:"Stable IDs prevent name drift.",steps:["Use P### / PRJ identifiers consistently.","Company project codes are attributes, not replacement primary keys.","Never infer ownership from display name alone."]},
 {title:"3 · Google Drive",summary:"Drive owns real files and permission boundaries.",steps:["Keep PDF/DWG/ETABS/photos/source evidence in Drive.","Do not copy private source files into public GitHub.","Expose only normalized links that are safe to publish."]},
 {title:"4 · CSV",summary:"Best for small flat current tables.",steps:["projects.csv owns public project-master current values.","Keep one row per project identity.","Validate allowed statuses and coordinates."]},
 {title:"5 · JSON",summary:"Best for nested current operational state.",steps:["current-works.json owns today's structured Daily Ops state.","Keep readiness and execution distinct.","Attach source_refs to material operational facts."]},
 {title:"6 · JSONL",summary:"Best for append-only change history.",steps:["One event per line.","Do not rewrite older history to simplify the present.","Use event IDs and source refs for traceability."]},
 {title:"7 · Google Sheets",summary:"Excellent human interface; weak as the only relational authority.",steps:["Use for entry/review/reporting where helpful.","Do not duplicate project-master truth independently.","Treat projections as projections."]},
 {title:"8 · Slack",summary:"Short human interaction and field evidence.",steps:["Keep tracker messages concise.","Ask only for unresolved facts.","Do not make a bare 'Here' or unlabeled photo mean DONE."]},
 {title:"9 · PostgreSQL / Neon",summary:"A future application backend, not a mandatory dependency today.",steps:["The SQL file defines PK/FK/constraints.","Current Pages runtime reads files directly.","Adopt live PostgreSQL/Neon when authenticated concurrent transactional writes justify it."],tip:"Schema contract ≠ live database connection."},
 {title:"10 · Project resources",summary:"Link files without copying them.",steps:["Drive owns bytes.","project-resources.json owns project→resource relationship metadata.","Respect Drive permissions."]},
 {title:"11 · Specialist modules",summary:"Keep each engine in its own repository.",steps:["Scheduling → JP_Scheduling_Work_and_Resources_Management.","Cost → JP_Cost_Estimation.","Structural → JP_Structural_Analysis.","CAD → JP_Computer-Aided-Drawings.","R&D → JP_Research-and-Development."]},
 {title:"12 · GitHub Actions",summary:"Validation and deployment evidence.",steps:["Verify the run belongs to the intended commit.","Require SUCCESS for the final head.","Use failures to fix source/configuration, not to bypass checks."]},
 {title:"13 · GitHub Pages",summary:"Presentation layer, not private storage.",steps:["Only public-safe content belongs in the published artifact.","Use one canonical production Pages owner/source per repository.","Experimental branches should build/test without overwriting production."]},
 {title:"14 · A9 governance",summary:"Rollback, provenance, readback and synchronization.",steps:["Take PRE before material mutation.","Never blind overwrite concurrent work.","Read back exact provider state.","Take finite POST and close Local/Main under the same sequence where applicable."]},
 {title:"15 · When to change architecture",summary:"Add complexity only when the current layer becomes the constraint.",steps:["Stay file-first while the team/volume fits.","Move secure write-back behind authentication/API.","Introduce PostgreSQL/Neon for multi-user transactions, permissions, complex queries or app backends.","Keep Drive for large/source files even after a database migration."]}
]};
const VISUALS={
"1":["05-slack-to-canonical.svg"],
"3":["01-workspace.svg","05-slack-to-canonical.svg","10-github-actions.svg"],
"7":["03-site-operations.svg","05-slack-to-canonical.svg","06-stock-vs-consumption.svg","04-project-detail.svg","10-github-actions.svg","09-sheets-projection.svg","12-a9-governance.svg"],
"15":["01-workspace.svg","02-project-map.svg","08-drive-resources.svg","11-storage-neon.svg","04-project-detail.svg","05-slack-to-canonical.svg","09-sheets-projection.svg","05-slack-to-canonical.svg","11-storage-neon.svg","08-drive-resources.svg","13-specialist-modules.svg","10-github-actions.svg","14-pages-production.svg","12-a9-governance.svg","15-architecture-change.svg"]
};
const VISUAL_META={
"01-workspace.svg":["Workspace → correct destination","Owner-facing directory routing users to the correct operational surface."],
"02-project-map.svg":["Project Map → stable project identity","Map context resolves to stable project identifiers before operational edits."],
"03-site-operations.svg":["Site Operations → portfolio attention","Portfolio scan highlights readiness, blockers and projects needing follow-up."],
"04-project-detail.svg":["Project detail → one-site operating view","Work, readiness, materials, evidence and resources stay distinct but connected."],
"05-slack-to-canonical.svg":["Slack evidence → canonical Daily Ops","Field evidence is validated and classified before current state and history change."],
"06-stock-vs-consumption.svg":["Stock ≠ consumption","Observed stock remains separate from actual usage or consumption evidence."],
"07-readiness-blockers.svg":["Readiness gates → execution decision","Materials, manpower, PPE, tools and preconditions determine readiness."],
"08-drive-resources.svg":["Drive file → project resource link","Source files remain permission-gated in Drive while project pages carry normalized links."],
"09-sheets-projection.svg":["Canonical state → Google Sheets projection","Validated state is projected to a human-friendly Sheet without creating competing truth."],
"10-github-actions.svg":["Commit → validation → Pages","The intended commit must pass checks and deployment before publication is trusted."],
"11-storage-neon.svg":["Choose storage by responsibility","CSV/JSON, Drive, Sheets, SQL contracts and PostgreSQL solve different storage problems."],
"12-a9-governance.svg":["A9 → recoverable change","PRE, bounded mutation, readback, POST and Local/Main acknowledgement preserve recoverability."],
"13-specialist-modules.svg":["Operations Hub → specialist engines","Scheduling, Cost, Structural, CAD and R&D keep specialist ownership outside Daily Ops."],
"14-pages-production.svg":["One canonical production Pages source","Experimental branches may test while the governed source owns production deployment."],
"15-architecture-change.svg":["Change architecture only at a real threshold","Introduce backend/database complexity only when authenticated transactional needs justify it."]
};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const root=document.body.dataset.root||"../";const depth=document.body.dataset.depth||"1";const pages=DATA[depth]||DATA["1"];
function href(u){return /^https?:/.test(u)?u:root+u}
document.getElementById("pages").innerHTML=pages.map((p,i)=>'<article class="guide-page"><div class="page-no">Page '+(i+1)+' of '+pages.length+'</div><h2>'+esc(p.title)+'</h2><p class="summary">'+esc(p.summary)+'</p><ol class="steps">'+p.steps.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ol>'+(p.tip?'<div class="callout">'+esc(p.tip)+'</div>':'')+(function(){const f=VISUALS[depth]?.[i];if(!f)return "";const m=VISUAL_META[f]||["Tutorial visual","JP AEC tutorial visual"];return '<figure class="visual"><img loading="lazy" src="'+esc(root+'guide/images/'+f)+'" alt="'+esc(m[1])+'"><figcaption><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></figcaption></figure>'})()+(p.links?'<div class="links">'+p.links.map(x=>'<a href="'+esc(href(x[1]))+'">'+esc(x[0])+' →</a>').join("")+'</div>':'')+'</article>').join("");
document.getElementById("print").addEventListener("click",()=>window.print());
document.querySelectorAll("[data-depth-link]").forEach(a=>{if(a.dataset.depthLink===depth)a.classList.add("active")});
